name: SinceBooster
version: '1.1'
main: net.danh.sincebooster.SinceBooster
api-version: '1.21'
authors: [ VoChiDanh ]
website: https://gitlab.com/sincerpg/SinceBooster
dependencies:
  server:
    MythicLib:
      load: BEFORE
      required: true
    MMOCore:
      load: BEFORE
      required: true
permissions:
  sincebooster.admin:
    description: Admin access to bypass configurations and force booster actions.
    default: op
  sincebooster.share:
    description: Allows players to share boosters with others.
    default: true
  sincebooster.share.offline:
    description: Allows boosters to stay active for receivers when the owner logs out.
    default: false